In [4]:
import pandas as pd
import requests
import requests as requests
from bs4 import BeautifulSoup
import time
import os
import bs4
from bs4 import BeautifulSoup
import pandas as pd
import scipy as sc
import numpy as np
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import time

<img src="https://i.ibb.co/cN4xb45/sportslogo.jpg"/>

# Crawling Data from "sports-reference" website, using selenium
### We used a function to get our attributes to a dataframe. We collected the attributes by players names in alphabetical order.

In [8]:
PATH = "C:\Program Files (x86)\chromedriver.exe"
driver = webdriver.Chrome(PATH)
driver.maximize_window()
main_data = list()

def attribute(driver):
    
    players = driver.find_elements(By.XPATH, '//*[@id="meta"]/div/h1/span')
    g = driver.find_elements(By.XPATH, '//*[@id="players_per_game"]/tfoot/tr/td[3]')
    gs = driver.find_elements(By.XPATH, '//*[@id="players_per_game"]/tfoot/tr/td[4]')
    mp = driver.find_elements(By.XPATH, '//*[@id="players_per_game"]/tfoot/tr/td[5]')
    fg = driver.find_elements(By.XPATH, '//*[@id="players_per_game"]/tfoot/tr/td[6]')
    fga = driver.find_elements(By.XPATH, '//*[@id="players_per_game"]/tfoot/tr/td[7]')
    fg1 = driver.find_elements(By.XPATH, '//*[@id="players_per_game"]/tfoot/tr/td[8]')
    p2 = driver.find_elements(By.XPATH, '//*[@id="players_per_game"]/tfoot/tr/td[9]')
    p2a = driver.find_elements(By.XPATH, '//*[@id="players_per_game"]/tfoot/tr/td[10]')
    p21 = driver.find_elements(By.XPATH, '//*[@id="players_per_game"]/tfoot/tr/td[11]')
    p3 = driver.find_elements(By.XPATH, '//*[@id="players_per_game"]/tfoot/tr/td[12]')
    p3a = driver.find_elements(By.XPATH, '//*[@id="players_per_game"]/tfoot/tr/td[13]')
    p31 = driver.find_elements(By.XPATH, '//*[@id="players_per_game"]/tfoot/tr/td[14]')
    ft = driver.find_elements(By.XPATH, '//*[@id="players_per_game"]/tfoot/tr/td[15]')
    fta = driver.find_elements(By.XPATH, '//*[@id="players_per_game"]/tfoot/tr/td[16]')
    ft1 = driver.find_elements(By.XPATH, '//*[@id="players_per_game"]/tfoot/tr/td[17]')
    orb = driver.find_elements(By.XPATH, '//*[@id="players_per_game"]/tfoot/tr/td[18]')
    drb = driver.find_elements(By.XPATH, '//*[@id="players_per_game"]/tfoot/tr/td[19]')

    data = []
    i = 0
    

    temporary_data = {'name': players[i].text, 'G': g[i].text, 'GS': gs[i].text,
                      'MP': mp[i].text, 'FG': fg[i].text, 'FGA': fga[i].text,
                      'FG%': fg1[i].text, 'P2': p2[i].text, '2PA': p2a[i].text,
                      '2P%': p21[i].text, '3P': p3[i].text, '3PA': p3a[i].text,
                      '3P%': p31[i].text, 'FT': ft[i].text, 'FTA': fta[i].text,
                      'FT%': ft1[i].text, 'ORB': orb[i].text, 'DRB': drb[i].text,
                      }

    data.append(temporary_data)
    return data


# Empty list for storing links
links = []
final_links =[]
listOfpSmall = []

str1 = ".html"
str2 = "/cbb/players/"

html_text=requests.get('https://www.sports-reference.com/cbb/players/a-index.html').text

soup = BeautifulSoup(html_text,'html.parser')


mtag = soup.find('div',attrs={"id":"content"})

links=[link['href'] for link in mtag.findAll("a")]



for link in links:
    if(link.endswith(str1) & link.startswith(str2)):
        final_links.append(link)
        
for link in final_links:        
        driver.get("https://www.sports-reference.com"+link);
        main_data += attribute(driver)
        
        

df = pd.DataFrame(main_data)        

df.to_csv(r'C:\Users\vikvi\0_NBA_PROJECT\Dataframe_A.csv',index=False)

<ipython-input-8-08e894d4f5b5>:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(PATH)

In [17]:
data = pd.read_csv('data\Dataframe_A.csv')
data.shape
data.head(10)

,name,G,GS,MP,FG,FGA,FG%,P2,2PA,2P%,3P,3PA,3P%,FT,FTA,FT%,ORB,DRB
0,Menghe a'Nyam,41.0,19.0,13.3,0.9,2.1,0.414,0.9,2.0,0.429,0.0,0.1,0.000,0.7,1.2,0.529,1.3,1.7
1,Jordan Aaberg,115.0,16.0,11.2,1.5,2.3,0.619,1.5,2.3,0.619,0.0,0.0,NaN,0.6,0.7,0.788,0.7,1.6
2,Karl Aaker,92.0,29.0,16.4,1.4,4.0,0.346,0.4,1.2,0.360,0.9,2.8,0.340,0.4,0.6,0.611,0.6,1.4
3,Steve Aaker,52.0,NaN,NaN,2.5,6.1,0.415,1.2,2.3,0.500,5.1,NaN,NaN,NaN,NaN,3.000,6.2,NaN
4,Waine Aalto,10.0,NaN,NaN,1.3,2.4,0.542,0.5,1.0,0.500,1.5,NaN,NaN,NaN,NaN,1.100,3.1,NaN
5,Mike Aaman,107.0,55.0,19.0,3.1,6.5,0.473,3.1,6.5,0.474,0.0,0.0,0.000,1.8,2.8,0.641,2.5,3.2
6,Craig Aamot,45.0,1.0,7.0,0.4,0.9,0.425,0.3,0.6,0.480,0.1,0.3,0.333,0.4,0.5,0.792,NaN,NaN
7,Art Aaron,108.0,66.0,25.9,4.5,9.9,0.453,NaN,NaN,0.478,NaN,NaN,0.293,2.0,3.0,0.673,3.5,1.7
8,Carlton Aaron,93.0,72.0,23.1,3.9,7.3,0.542,3.9,7.3,0.542,0.0,0.0,NaN,1.9,3.8,0.486,NaN,NaN
9,David Aaron,82.0,3.0,8.9,0.4,0.7,0.500,0.3,0.7,0.500,0.0,0.0,0.000,0.4,0.7,0.600,NaN,NaN

In [19]:

PATH = "C:\Program Files (x86)\chromedriver.exe"
driver = webdriver.Chrome(PATH)
driver.maximize_window()
main_data = list()


links = []
final_links =[]
listOfpSmall = []

str1 = ".html"
str2 = "/cbb/players/"

html_text=requests.get('https://www.sports-reference.com/cbb/players/b-index.html').text

soup = BeautifulSoup(html_text,'html.parser')


mtag = soup.find('div',attrs={"id":"content"})

links=[link['href'] for link in mtag.findAll("a")]



for link in links:
    if(link.endswith(str1) & link.startswith(str2)):
        final_links.append(link)
        
for link in final_links:        
        driver.get("https://www.sports-reference.com"+link);
        main_data += attribute(driver)
        
        

df = pd.DataFrame(main_data)        

df.to_csv(r'C:\Users\vikvi\0_NBA_PROJECT\Dataframe_B.csv',index=False)

<ipython-input-19-c441d4086642>:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(PATH)

In [20]:
data_B = pd.read_csv('data\Dataframe_B.csv')
data_B.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10510 entries, 0 to 10509
Data columns (total 18 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    10510 non-null  object
 1   G       10364 non-null  float64
 2   GS      6231 non-null   float64
 3   MP      6553 non-null   float64
 4   FG      10356 non-null  float64
 5   FGA     10132 non-null  float64
 6   FG%     9929 non-null   float64
 7   P2      9339 non-null   float64
 8   2PA     9239 non-null   float64
 9   2P%     9044 non-null   float64
 10  3P      8858 non-null   float64
 11  3PA     6787 non-null   float64
 12  3P%     5098 non-null   float64
 13  FT      6953 non-null   float64
 14  FTA     7024 non-null   float64
 15  FT%     9633 non-null   float64
 16  ORB     8014 non-null   float64
 17  DRB     4387 non-null   float64
dtypes: float64(17), object(1)
memory usage: 1.4+ MB

In [ ]:
links = []
final_links =[]
listOfpSmall = []

str1 = ".html"
str2 = "/cbb/players/"

html_text=requests.get('https://www.sports-reference.com/cbb/players/c-index.html').text

soup = BeautifulSoup(html_text,'html.parser')


mtag = soup.find('div',attrs={"id":"content"})

links=[link['href'] for link in mtag.findAll("a")]



for link in links:
    if(link.endswith(str1) & link.startswith(str2)):
        final_links.append(link)
        
for link in final_links:        
        driver.get("https://www.sports-reference.com"+link);
        main_data += attribute(driver)
        
        

df = pd.DataFrame(main_data)        

df.to_csv(r'C:\Users\vikvi\0_NBA_PROJECT\Dataframe_C.csv',index=False)

In [11]:
data = pd.read_csv('data\Dataframe_C.csv')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7757 entries, 0 to 7756
Data columns (total 18 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    7757 non-null   object
 1   G       7643 non-null   float64
 2   GS      4527 non-null   float64
 3   MP      4733 non-null   float64
 4   FG      7636 non-null   float64
 5   FGA     7454 non-null   float64
 6   FG%     7307 non-null   float64
 7   P2      6938 non-null   float64
 8   2PA     6866 non-null   float64
 9   2P%     6705 non-null   float64
 10  3P      6554 non-null   float64
 11  3PA     4975 non-null   float64
 12  3P%     3765 non-null   float64
 13  FT      5074 non-null   float64
 14  FTA     5085 non-null   float64
 15  FT%     7060 non-null   float64
 16  ORB     5920 non-null   float64
 17  DRB     3154 non-null   float64
dtypes: float64(17), object(1)
memory usage: 1.1+ MB

In [ ]:
links = []
final_links =[]
listOfpSmall = []

str1 = ".html"
str2 = "/cbb/players/"

html_text=requests.get('https://www.sports-reference.com/cbb/players/w-index.html').text

soup = BeautifulSoup(html_text,'html.parser')


mtag = soup.find('div',attrs={"id":"content"})

links=[link['href'] for link in mtag.findAll("a")]



for link in links:
    if(link.endswith(str1) & link.startswith(str2)):
        final_links.append(link)

del final_links[0]
        

for link in final_links:        
        driver.get("https://www.sports-reference.com"+link);
        main_data += attribute(driver)
        
        

df = pd.DataFrame(main_data)        

df.to_csv(r'C:\Users\vikvi\0_NBA_PROJECT\Dataframe_W.csv',index=False)

In [10]:
data2 = pd.read_csv('data\Dataframe_W.csv')
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7809 entries, 0 to 7808
Data columns (total 18 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    7809 non-null   object
 1   G       7691 non-null   float64
 2   GS      4794 non-null   float64
 3   MP      5008 non-null   float64
 4   FG      7687 non-null   float64
 5   FGA     7556 non-null   float64
 6   FG%     7399 non-null   float64
 7   P2      6866 non-null   float64
 8   2PA     6815 non-null   float64
 9   2P%     6717 non-null   float64
 10  3P      6569 non-null   float64
 11  3PA     5154 non-null   float64
 12  3P%     3916 non-null   float64
 13  FT      5379 non-null   float64
 14  FTA     5406 non-null   float64
 15  FT%     7178 non-null   float64
 16  ORB     5831 non-null   float64
 17  DRB     3314 non-null   float64
dtypes: float64(17), object(1)
memory usage: 1.1+ MB

In [ ]:
links = []
final_links =[]
listOfpSmall = []

str1 = ".html"
str2 = "/cbb/players/"

html_text=requests.get('https://www.sports-reference.com/cbb/players/m-index.html').text

soup = BeautifulSoup(html_text,'html.parser')


mtag = soup.find('div',attrs={"id":"content"})

links=[link['href'] for link in mtag.findAll("a")]



for link in links:
    if(link.endswith(str1) & link.startswith(str2)):
        final_links.append(link)
        

for link in final_links:        
        driver.get("https://www.sports-reference.com"+link);
        main_data += attribute(driver)
        
        

df = pd.DataFrame(main_data)        

df.to_csv(r'C:\Users\vikvi\0_NBA_PROJECT\data\Dataframe_M.csv',index=False)

In [9]:
data2 = pd.read_csv('data\Dataframe_M.csv')
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10340 entries, 0 to 10339
Data columns (total 18 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    10340 non-null  object
 1   G       10200 non-null  float64
 2   GS      6135 non-null   float64
 3   MP      6348 non-null   float64
 4   FG      10190 non-null  float64
 5   FGA     9959 non-null   float64
 6   FG%     9770 non-null   float64
 7   P2      9209 non-null   float64
 8   2PA     9106 non-null   float64
 9   2P%     8950 non-null   float64
 10  3P      8712 non-null   float64
 11  3PA     6604 non-null   float64
 12  3P%     4969 non-null   float64
 13  FT      6789 non-null   float64
 14  FTA     6850 non-null   float64
 15  FT%     9466 non-null   float64
 16  ORB     7922 non-null   float64
 17  DRB     4271 non-null   float64
dtypes: float64(17), object(1)
memory usage: 1.4+ MB

In [ ]:
links = []
final_links =[]
listOfpSmall = []

str1 = ".html"
str2 = "/cbb/players/"

html_text=requests.get('https://www.sports-reference.com/cbb/players/h-index.html').text

soup = BeautifulSoup(html_text,'html.parser')


mtag = soup.find('div',attrs={"id":"content"})

links=[link['href'] for link in mtag.findAll("a")]



for link in links:
    if(link.endswith(str1) & link.startswith(str2)):
        final_links.append(link)
        

for link in final_links:        
        driver.get("https://www.sports-reference.com"+link);
        main_data += attribute(driver)
        
        

df = pd.DataFrame(main_data)        

df.to_csv(r'C:\Users\vikvi\0_NBA_PROJECT\data\Dataframe_H.csv',index=False)

In [8]:
data2 = pd.read_csv('data\Dataframe_H.csv')
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8303 entries, 0 to 8302
Data columns (total 18 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    8303 non-null   object
 1   G       8160 non-null   float64
 2   GS      4952 non-null   float64
 3   MP      5202 non-null   float64
 4   FG      8150 non-null   float64
 5   FGA     7981 non-null   float64
 6   FG%     7827 non-null   float64
 7   P2      7387 non-null   float64
 8   2PA     7317 non-null   float64
 9   2P%     7192 non-null   float64
 10  3P      7020 non-null   float64
 11  3PA     5404 non-null   float64
 12  3P%     4112 non-null   float64
 13  FT      5512 non-null   float64
 14  FTA     5544 non-null   float64
 15  FT%     7607 non-null   float64
 16  ORB     6247 non-null   float64
 17  DRB     3402 non-null   float64
dtypes: float64(17), object(1)
memory usage: 1.1+ MB

In [ ]:
links = []
final_links =[]
listOfpSmall = []

str1 = ".html"
str2 = "/cbb/players/"

html_text=requests.get('https://www.sports-reference.com/cbb/players/a-index.html').text

soup = BeautifulSoup(html_text,'html.parser')


mtag = soup.find('div',attrs={"id":"content"})

links=[link['href'] for link in mtag.findAll("a")]



for link in links:
    if(link.endswith(str1) & link.startswith(str2)):
        final_links.append(link)

for link in final_links:        
        driver.get("https://www.sports-reference.com"+link);
        main_data += attribute(driver)
        
        

df = pd.DataFrame(main_data)        

df.to_csv(r'C:\Users\vikvi\0_NBA_PROJECT\Dataframe_X_A.csv',index=False)

In [7]:
data = pd.read_csv('data\Dataframe_X.csv')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 25 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    8 non-null      object
 1   G       8 non-null      int64
 2   GS      8 non-null      int64
 3   MP      8 non-null      float64
 4   FG      8 non-null      float64
 5   FGA     8 non-null      float64
 6   FG%     7 non-null      float64
 7   P2      8 non-null      float64
 8   2PA     8 non-null      float64
 9   2P%     7 non-null      float64
 10  3P      8 non-null      float64
 11  3PA     8 non-null      float64
 12  3P%     5 non-null      float64
 13  FT      8 non-null      float64
 14  FTA     8 non-null      float64
 15  FT%     6 non-null      float64
 16  ORB     8 non-null      float64
 17  DRB     8 non-null      float64
 18  TRB     8 non-null      float64
 19  AST     8 non-null      float64
 20  STL     8 non-null      float64
 21  BLK     8 non-null      float64
 22  TOV     8 non-null      float64
 23  PF      8 non-null      float64
 24  PTS     8 non-null      float64
dtypes: float64(22), int64(2), object(1)
memory usage: 1.7+ KB

In [ ]:
links = []
final_links =[]
listOfpSmall = []

str1 = ".html"
str2 = "/cbb/players/"

html_text=requests.get('https://www.sports-reference.com/cbb/players/w-index.html').text

soup = BeautifulSoup(html_text,'html.parser')


mtag = soup.find('div',attrs={"id":"content"})

links=[link['href'] for link in mtag.findAll("a")]



for link in links:
    if(link.endswith(str1) & link.startswith(str2)):
        final_links.append(link)
        
for link in final_links:        
        driver.get("https://www.sports-reference.com"+link);
        main_data += attribute(driver)
        
        

df = pd.DataFrame(main_data)        

df.to_csv(r'C:\Users\vikvi\0_NBA_PROJECT\Dataframe_Z.csv',index=False)

In [6]:
data = pd.read_csv('data\Dataframe_Z.csv')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 407 entries, 0 to 406
Data columns (total 18 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    407 non-null    object
 1   G       397 non-null    float64
 2   GS      222 non-null    float64
 3   MP      221 non-null    float64
 4   FG      397 non-null    float64
 5   FGA     389 non-null    float64
 6   FG%     377 non-null    float64
 7   P2      367 non-null    float64
 8   2PA     364 non-null    float64
 9   2P%     358 non-null    float64
 10  3P      343 non-null    float64
 11  3PA     242 non-null    float64
 12  3P%     169 non-null    float64
 13  FT      237 non-null    float64
 14  FTA     238 non-null    float64
 15  FT%     364 non-null    float64
 16  ORB     323 non-null    float64
 17  DRB     153 non-null    float64
dtypes: float64(17), object(1)
memory usage: 57.4+ KB

<img src="https://i.ibb.co/kHBzRcF/logo.jpg"/>

# Crawling from Official NBA website
### We collected information about players picks in first draft - of all times.

In [ ]:
PATH = "C:\Program Files (x86)\chromedriver.exe"
driver=webdriver.Chrome(PATH)
driver.get("https://www.nba.com/stats/draft/history/?Season=")

In [ ]:

players = driver.find_elements(By.XPATH,'/html/body/main/div/div/div[2]/div/div/nba-stat-table/div[2]/div[1]/table/tbody/tr/td[1]')
rpicks = driver.find_elements(By.XPATH,'/html/body/main/div/div/div[2]/div/div/nba-stat-table/div[2]/div[1]/table/tbody/tr/td[5]')
result=[]

for i in range(len(players)):
    temp={'Name':players[i].text,'DraftPick':rpicks[i].text}

    result.append(temp)
    
df=pd.DataFrame(result)


df.to_csv(r'C:\Users\vikvi\0_FINAL\Dataframe_NBA_Correct.csv',index=False)

In [15]:
data = pd.read_csv('data\Dataframe_NBA_Correct.csv')
data.info()
data.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8143 entries, 0 to 8142
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       8143 non-null   object
 1   DraftPick  8143 non-null   int64
dtypes: int64(1), object(1)
memory usage: 127.4+ KB

               Name  DraftPick
0     Gail Goodrich          0
1      Bill Bradley          0
2       Bill Buntin          0
3      Walt Hazzard          0
4     George Wilson          0
5       Tom Thacker          0
6       Jerry Lucas          0
7  Dave DeBusschere          0
8  Wilt Chamberlain          0
9         Bob Ferry          0